# Échecs d'authentification Vaultwarden
# Ligne de journal ciblée :
# [2026-08-24 21:30:00.000][vaultwarden::api::identity][ERROR] Username or password is incorrect. Try again. IP: 203.0.113.7. Username: user@exemple.lu.
[INCLUDES]
before = common.conf

[Definition]
failregex = ^.*Username or password is incorrect\. Try again\. IP: <ADDR>\. Username:.*$
            ^.*Invalid TOTP code.*IP: <ADDR>.*$
            ^.*Username or password is incorrect\. Try again\. IP: <ADDR>\.$
ignoreregex =
journalmatch =
